server:
  port: 7003
eureka:
  instance:
    #hostname: localhost
    hostname: eureka7003
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机版本的
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7001:7001/eureka
